name: Publish VSCE Package

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: lannonbr/vsce-action@3.0.0
              with:
                  args: "publish -p $VSCE_TOKEN"
              env:
                  VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
